# -*- coding: utf-8 -*-
"""Task-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZmVnfLtlSpzcokJHgubS1JenU_URFBI
"""

def caesar_cipher(text, shift):
    """Core logic to shift characters."""
    result = ""
    for char in text:
        if char.isalpha():
            base = ord('A') if char.isupper() else ord('a')
            shifted_char = chr((ord(char) - base + shift) % 26 + base)
            result += shifted_char
        else:
            result += char
    return result

def main():
    while True:
        print("\n--- Caesar Cipher Menu ---")
        print("1. Encode a message")
        print("2. Decode a message")
        print("3. Exit")

        choice = input("\nSelect an option (1-3): ")

        if choice == '1':
            message = input("Enter the message to encode: ")
            shift = int(input("Enter the shift value: "))
            encrypted = caesar_cipher(message, shift)
            print(f"\nEncrypted Result: {encrypted}")

        elif choice == '2':
            message = input("Enter the message to decode: ")
            shift = int(input("Enter the shift value: "))
            decrypted = caesar_cipher(message, -shift)
            print(f"\nDecrypted Result: {decrypted}")

        elif choice == '3':
            print("Exited")
            break

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

if __name__ == "__main__":
    main()